### ISSUE TITLE
Problems building template Haskell

### ISSUE THREAD

**Issue by commandodev** [boothead/ohm-examples#4]
With  b87498323 checked out:

``` shell
ben@xps:~/dev/ghcjs/examples/todo-mvc|haskell-ng⚡
⇒  ls -la
total 68
drwxrwxr-x 7 ben ben  4096 Mar  2 18:05 .
drwxrwxr-x 6 ben ben  4096 Jan  6 06:12 ..
drwxrwxr-x 2 ben ben  4096 Dec 31 15:17 build
-rw-rw-r-- 1 ben ben  1488 Feb 28 09:16 build.nix
-rw-rw-r-- 1 ben ben    16 Nov 27 06:10 cabal.config
-rw-rw-r-- 1 ben ben   528 Mar  1 21:38 default.nix
drwxr-xr-x 4 ben ben  4096 Mar  2 20:13 dist
drwxrwxr-x 3 ben ben  4096 Jan 19 08:14 docs
-rw-rw-r-- 1 ben ben 11514 Nov 27 06:10 LICENSE.txt
-rwxrwxr-x 1 ben ben   291 Dec 24 15:13 make.sh
lrwxrwxrwx 1 ben ben    13 Jan  4 06:23 nixpkgs -> ../../nixpkgs
lrwxrwxrwx 1 ben ben     9 Jan  4 06:22 oHm -> ../../oHm
-rw-rw-r-- 1 ben ben  1435 Mar  2 17:48 ohm-todo-mvc.cabal
-rw-rw-r-- 1 ben ben     0 Dec 30 15:39 .projectile
-rw-rw-r-- 1 ben ben    46 Nov 27 06:10 Setup.hs
-rw-rw-r-- 1 ben ben   311 Mar  1 21:37 shell.nix
drwxrwxr-x 2 ben ben  4096 Mar  2 20:17 src
drwxrwxr-x 2 ben ben  4096 Jan  7 08:38 static
lrwxrwxrwx 1 ben ben    17 Mar  1 21:37 virtual-dom -> ../../virtual-dom
ben@xps:~/dev/ghcjs/examples/todo-mvc|haskell-ng⚡
⇒  nix-shell -I . --command "cabal configure --ghcjs"
Warning: The package list for 'hackage.haskell.org' is 268.5 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Configuring ohm-todo-mvc-0.1.0.0...
ben@xps:~/dev/ghcjs/examples/todo-mvc|haskell-ng⚡
⇒  nix-shell -I . --command "cabal build"            
Building ohm-todo-mvc-0.1.0.0...
Preprocessing executable 'todo-mvc' for ohm-todo-mvc-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/todo-mvc/todo-mvc-tmp/Main.js_o )
Linking Template Haskell (ThRunner1)

/tmp/ghc939_0/ghc939_45.jspp:205:28:
     warning: trigraph ??/ ignored, use -trigraphs to enable [-Wtrigraphs]
         compliantExecNpcg = /()??/.exec("")[1] === undef,
     ^
uncaught exception in Haskell main thread: ReferenceError: navigator is not defined
ReferenceError: navigator is not defined
    at Object.eval (eval at h$loadCodeStr (/nix/store/w75wnmyfpgg7nsi3kxapy8kwqh77pr1d-ghcjs-0.1.0/lib/ghcjs-0.1.0/thrunner.js:139:10), <anonymous>:7457:17)

    at Object../keys (eval at h$loadCodeStr (/nix/store/w75wnmyfpgg7nsi3kxapy8kwqh77pr1d-ghcjs-0.1.0/lib/ghcjs-0.1.0/thrunner.js:139:10), <anonymous>:7908:4)
<no location info>:
    Data.Binary.Get.runGet at position 0: demandInput: not enough bytes
    at s (eval at h$loadCodeStr (/nix/store/w75wnmyfpgg7nsi3kxapy8kwqh77pr1d-ghcjs-0.1.0/lib/ghcjs-0.1.0/thrunner.js:139:10), <anonymous>:4624:540)
    at eval (eval at h$loadCodeStr (/nix/store/w75wnmyfpgg7nsi3kxapy8kwqh77pr1d-ghcjs-0.1.0/lib/ghcjs-0.1.0/thrunner.js:139:10), <anonymous>:4624:591)
    at Object.component-emitter (eval at h$loadCodeStr (/nix/store/w75wnmyfpgg7nsi3kxapy8kwqh77pr1d-ghcjs-0.1.0/lib/ghcjs-0.1.0/thrunner.js:139:10), <anonymous>:6358:14)
    at s (eval at h$loadCodeStr (/nix/store/w75wnmyfpgg7nsi3kxapy8kwqh77pr1d-ghcjs-0.1.0/lib/ghcjs-0.1.0/thrunner.js:139:10), <anonymous>:4624:540)
    at eval (eval at h$loadCodeStr (/nix/store/w75wnmyfpgg7nsi3kxapy8kwqh77pr1d-ghcjs-0.1.0/lib/ghcjs-0.1.0/thrunner.js:139:10), <anonymous>:4624:591)
```

**Comment by mschristiansen** [comment]
Same error when trying to use 'cabal build', but the code is actually built and works. I'm using the cabal sandbox and adding the oHm sources instead of nix packages and symlinks.

Currently stopping me from using oHm in my own projects.

**Comment by jkozlowski** [comment]
Seeing a similar problem (but I compiled ghcjs manually) on https://github.com/boothead/ohm-examples/commit/f703757173c17e99dcf43490b4f7ccaa2c7ef8e3:

```
Building todomvc-ghcjs-0.1.0.0...
Preprocessing executable 'todomvc-ghcjs' for todomvc-ghcjs-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/todomvc-ghcjs/todomvc-ghcjs-tmp/Main.js_o )
Linking Template Haskell (ThRunner1)
uncaught exception in Haskell main thread: ReferenceError: document is not defined
ReferenceError: document is not defined
    at eval (eval at h$loadCodeStr (/Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:139:10), <anonymous>:1142:12)
    at eval (eval at h$loadCodeStr (/Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:139:10), <anonymous>:1171:3)
    at eval (native)
    at Object.h$loadCodeStr [as loadCodeStr] (/Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:139:10)
    at Object.h$loadCode [as loadCode] (/Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:147:10)
    at h$$ghcjszu2U6CT3su9VuHXMTtRe30dXZCGHCJSziPrimziTHziEval_dJ (eval at h$loadCodeStr (/Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:139:10), <anonymous>:41465:16)
    at h$mainLoop (eval at h$loadCodeStr (/Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:139:10), <anonymous>:10462:25)
    at eval (eval at h$loadCodeStr (/Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:139:10), <anonymous>:10945:13)
    at /Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:95:9
    at h$processQueue (/Users/jakubkozlowski/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/thrunner.js:71:13)

<no location info>:
    Data.Binary.Get.runGet at position 0: demandInput: not enough bytes
```

**Comment by jkozlowski** [comment]
Managed to fix mine; it is beacuse of https://github.com/boothead/oHm/blob/master/vendor/keymaster.js having references to the browser document object, which doesn't exist when ran through nodejs. Moving the types (and hence the TH magic for lenses) to a separate module fixed this.

**Comment by commandodev** [comment]
Thanks @jkozlowski  - sorry I missed this update. @luite is this useful info for you?

**Comment by luite** [comment]
Yeah this is a general problem of how TH is run. The code has to work under the node.js environment, otherwise it breaks.

We could perhaps add some workarounds, like preprocessor options that exclude code from being linked when running TH, or add some thin browser compatibility layer that would at least get rid of some undefined variable errors. Does anyone have any preference or suggestions here?
